apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: NAMESPACE_PLACEHOLDER
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "20"
    persistentvolumeclaims: "5"
    services: "10"